container: aozora0000/jenkins-ci-php:latest
steps:
    - name: composerインストール
      code: composer install
    - name: PHPUNITテスト開始
      code: phpunit
notify:
    - service: idobata
      token: $IDOBATA_TOKEN
